encoding: switch to iconv-based conversions
Always handle internally as UTF-8, that is, allow conversion of input
from any charset and conversion to any charset.

- switch conditional processing of UTF-8 to the only processing
  supported
- convert input to UTF-8
- convert output from UTF-8
- drop custom mapping tables of sgml entities to latin-1 and ascii
  representation, let iconv deal with the conversions/transliterations
- introduce iconvstream class, to deal with the conversion while
  reading/writing
- in the scanner, treat UTF-8 sequences as a single char by packing into
  a single int
- add check for libiconv to configure, and use resulting libs in
  Makefile

Signed-off-by: Fabian Groffen <grobian@gentoo.org>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -123,6 +123,35 @@ else
 fi;
 
 #
+# $ICONV_LIBRARIES
+#
+
+$echo 'Checking for iconv libraries... \c';
+ICONV_LIBRARIES=unknown;
+cat >$tmp_file.C <<EOF;
+#include <iconv.h>
+int main() {
+  iconv_open("", "");
+  return 0;
+}
+EOF
+for i in "" "-liconv"; do
+  if $CXX $tmp_file.C $i -o $tmp_file 2>/dev/null; then
+    ICONV_LIBRARIES="$i";
+    break;
+  fi;
+done;
+if test "$ICONV_LIBRARIES" = unknown; then
+  $echo "Error: Could not determine the library for the iconv API.";
+  exit 1;
+fi;
+if test "$ICONV_LIBRARIES" = ""; then
+  $echo "no extra libraries required";
+else
+  $echo "use \"$ICONV_LIBRARIES\"";
+fi;
+
+#
 # $BOOL_DEFINITION
 #
 
@@ -276,6 +305,7 @@ cmd=sed;
 for i in \
   SYS_POLL_MISSING \
   SOCKET_LIBRARIES \
+  ICONV_LIBRARIES \
   CXX \
   BOOL_DEFINITION \
   EXPLICIT \
